import FFT from 'fft.js';
const $=id=>document.getElementById(id),fft=new FFT(128);let state;
function transform(h){const input=Array(128).fill(0);h.forEach((v,i)=>input[i]=v);const out=fft.createComplexArray();fft.transform(out,fft.toComplexArray(input));return out;}
function response(h){const H=transform(h),weighted=transform(h.map((v,i)=>i*v)),magnitude=[],delay=[];for(let k=0;k<=64;k++){const re=H[2*k],im=H[2*k+1],norm=re*re+im*im;magnitude.push(Math.sqrt(norm));delay.push((weighted[2*k]*re+weighted[2*k+1]*im)/norm);}const energy=h.reduce((s,v)=>s+v*v,0);let sum=0;const cumulative=h.map(v=>(sum+=v*v)/energy);return {h,H,magnitude,delay,energy,cumulative};}
function calculate(){const a=+$('a').value,b=+$('b').value,ra=$('ra').checked,rb=$('rb').checked,k=+$('k').value,p=ra?[a,-1]:[1,-a],q=rb?[b,-1]:[1,-b],minimum=response([1,-a-b,a*b]),selected=response([p[0]*q[0],p[0]*q[1]+p[1]*q[0],p[1]*q[1]]);state={a,b,ra,rb,k,zeros:[ra?1/a:a,rb?1/b:b],minimum,selected,error:Math.max(...minimum.magnitude.map((v,i)=>Math.abs(v-selected.magnitude[i])))};}
function plot(id,first,second){const c=$(id),r=c.getBoundingClientRect();c.width=Math.round(r.width*2);c.height=Math.round(r.height*2);const g=c.getContext('2d');g.scale(2,2);g.font='13px system-ui';const W=r.width,H=r.height,lo=Math.min(0,...first,...second),hi=Math.max(1,...first,...second),range=hi-lo,x=k=>45+k/64*(W-63),y=v=>22+(hi-v)/range*(H-55);g.textAlign='right';g.fillStyle='#58675f';for(const v of [lo,(lo+hi)/2,hi]){g.strokeStyle='#e0e7e3';g.beginPath();g.moveTo(45,y(v));g.lineTo(W-18,y(v));g.stroke();g.fillText(v.toFixed(1),39,y(v)+4);}g.textAlign='center';[0,16,32,48,64].forEach(k=>g.fillText((k/64).toFixed(2),x(k),H-8));g.strokeStyle='#9ba7a0';g.setLineDash([3,4]);g.beginPath();g.moveTo(x(state.k),18);g.lineTo(x(state.k),H-30);g.stroke();g.setLineDash([]);for(const [a,color,dash] of [[first,'#16664e',[]],[second,'#b43c64',[5,4]]]){g.strokeStyle=color;g.lineWidth=2;g.setLineDash(dash);g.beginPath();a.forEach((v,k)=>k?g.lineTo(x(k),y(v)):g.moveTo(x(k),y(v)));g.stroke();}g.setLineDash([]);}
function draw(){plot('magnitude',state.minimum.magnitude,state.selected.magnitude);plot('delay',state.minimum.delay,state.selected.delay);}
function render(){calculate();const s=state;$('oa').textContent=s.a.toFixed(2);$('ob').textContent=s.b.toFixed(2);$('ok').textContent=(s.k/64).toFixed(3);$('zeros').textContent='Selected zeros: '+s.zeros.map(v=>v.toFixed(3)).join(', ');$('extra').textContent=(s.selected.delay[s.k]-s.minimum.delay[s.k]).toFixed(5);$('error').textContent=s.error.toExponential(1);$('energy').textContent=s.minimum.energy.toFixed(5);$('rows').innerHTML=s.minimum.h.map((v,i)=>'<tr><td>'+i+'</td><td>'+v.toFixed(3)+'</td><td>'+s.selected.h[i].toFixed(3)+'</td><td>'+(100*s.minimum.cumulative[i]).toFixed(2)+'%</td><td>'+(100*s.selected.cumulative[i]).toFixed(2)+'%</td></tr>').join('');draw();}
['a','b','k'].forEach(id=>$(id).addEventListener('input',render));['ra','rb'].forEach(id=>$(id).addEventListener('change',render));$('both').addEventListener('click',()=>{$('ra').checked=true;$('rb').checked=true;render();});$('neither').addEventListener('click',()=>{$('ra').checked=false;$('rb').checked=false;render();});$('reset').addEventListener('click',()=>{$('a').value=.6;$('b').value=.3;$('ra').checked=true;$('rb').checked=false;$('k').value=16;render();});$('export').addEventListener('click',()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.href=url;a.download='zero-reflection.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});window.addEventListener('resize',draw);render();
